// Generated by Selenium IDE
import { Builder, By } from 'selenium-webdriver';

describe('Makes an empty donation', function () {
  jest.setTimeout(60000);
  let driver;
  // eslint-disable-next-line no-unused-vars
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it('Makes an empty donation', async function () {
    // Test name: Makes an empty donation
    // Step # | name | target | value
    // 1 | open | / |
    await driver.get('http://localhost:3000/');
    // 2 | setWindowSize | 1920x1080 |
    await driver.manage().window().setRect({ width: 1920, height: 1080 });
    // 3 | click | xpath=//form/div/button |
    await driver.findElement(By.xpath('//form/div/button')).click();
    // 4 | webdriverChooseOkOnVisibleConfirmation | xpath=//body/div[4]/div/div |
    // await driver.switchTo().alert().accept();
  });
});
